// GENERAL
export const CHANGE_THEME = 'CHANGE_THEME'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

// ADDICTION
export const ADD_ADDICTION = 'ADD_ADDICTION'
export const LOAD_ADDICTIONS = 'LOAD_ADDICTIONS'
export const REMOVE_ADDICTION = 'REMOVE_ADDICTION'
